env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:jsdoc/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - jsdoc
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - 2
    - 120
    - 4
  no-console: 0
  import/no-cycle: 0
  import/extensions: 0
  sort-imports:
    - 2
    - ignoreCase: true
  jsdoc/no-undefined-types: 0