language: node_js
node_js:
  - 14
services:
  - docker
env:
  global:
  - secure: WMIJAVR5eaa//RUAQMeiPahN/xBihxvex9+BaYmRjuIJQStjR952IRYjEDr6SIAshLEvKvVPp5JEt8ti+vt+0pX1/bgTPi8ofbDmvvHyrnUpC0h1w8PkEFihh4zOp+Y1yectb4dYTnlwfQUVVtvIzYDgUBIaDjEjUp/H+Kc+F5Oqtb90KjTkEDiau9GsNW3GFW9PEocLfTppFVWVimB/1wBfF4X5nIGMePCc/Mmd6PBAQxZH0Pd0Bs0radUyPxtDj3XI+ZSPPHyturyIwISdfla0sZbBtJTbEqn485GxrYid9XPAZoiR8v9N6KnZ5dVJIwswTBhPpmVOPkDg03hfWtkmUUwy3T/DoCrY+NbXLvjc1dkLJcmyXICVFJHhw7xa+qtHbEtfRkXoXJxk88FobvnCJBl9jCFvDCB1SdblthyNLYxkGHz8AEyQ2wO9RUz6RgPgwGAzkfjWHmghNlhhS6Z2+Eyrf8JY2jnjPyPjClzYmZ2OLALMeTznu3jrrE8hxtvhfFUUjM+FafrCAOW7Wc+K2btTs034YWmO2Dqr4JN1K6a+/uFnFwRhWziAPOKI1aLHxnY7Uwv1OFM7cvszs3pbwdC0ItbrqAUU79yxKyNpQ+dFCVYjGssAAN57fIihRRQn2ocld8AsmcR8EUbgDL0pPtdg+NUZG9skiAJnkno=
  - secure: aCxzRiikYAtrba9r5XERQMtD4fJb8Y/9hukj6KQ3P0bSMZZrtNk7NBmw3kBCSC7R11S82FIUF++uGs4kaqL4tFZ2c91QaTpIAOYLFhwkb1Gp/jsHbLlUVuFu54hwDy9QV5CCYPROR31V+5KiAAjU67MimN7i3rCFpkZdb4rjm7HfW8E4hWGkaTQDtSD9r1Ga2SLiy3Ctogp5KLIQPcrWSe9q0HUY6sy+KYAMhX36xkhypDvfBC/ptsrqGTVHIDUQ9PA3k2zFGoQSv6G6iJGyQMyX0g3JplogBIPkq1Xwh/LilKVyLzSyKGvt7UJoag812hNYOBbgcYtt8KiNWHOKJa1J5V2KilogP8psUuM3tPvkEiklHrLbbG4P6e2Zx6XxXBfe//8r4Dzke1u65EnahIPCUy1M5kBRxJuMqwWxGWRs4usDKHAKGRxV8M4B9EMNzUv4R4Q+0HTr4xCbWphD6c8I5PQkKF0+cT2If4jIo6mU1QuMu12h501P+DDJeVszEj/DDyAcckKLQYJzyJoZaXKRxEY2FeFyh7R1Lny0txFYjW1GQzzLXfD5xpuz56cNklBDBTuHjER+QNM+xfCdjM9WMSHAyz5W4jf7LkX2ePx38M6dsigKk8z19tBKU7/MGK+lK4VPKBhvSSB/LeTIOiMWHBLqpaaqaoi9nTWJzPQ=
script:
  - npm ci
  - make test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - PKG_VER=$(./package_version.sh) make build_dockerfile
  - docker push adlerneves/trustly-challenge-github-scraper
